Repository RobertoNittolo/jmonkeyengineW25, pull requests merged in 2025-03, with the labels that each got.

#20 Refactor: OSVR_ViewportDescription Classes for Clones.
  jme3-vr/src/main/java/com/jme3/system/osvr/OSVR_ViewportDescription.java
  jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanager/OSVR_ViewportDescription.java
  jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OSVR_ViewportDescription.java
Labels: duplicate, Group 08, Remove Software Clone

#18 refactor: Centralize OSVR_RGB to resolve duplication
  jme3-vr/src/main/java/com/jme3/system/osvr/common/OSVR_RGB.java
  jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanager/OSVR_RGB.java
  jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanager/OsvrRenderManagerLibrary.java
  jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OSVR_RGB.java
  jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OsvrRenderManagerOpenGLLibrary.java
Labels: Group 08, Remove Software Clone

#24 Refactor: Add a helper method to remove duplication in adjoint and inverse methods
  jme3-core/src/main/java/com/jme3/math/Matrix4f.java
Labels: Group 08, Remove Software Clone

#22 Refactored code to avoid duplication of distance method in 3 classes …
  jme3-core/src/main/java/com/jme3/light/LightProbe.java
  jme3-core/src/main/java/com/jme3/light/PointLight.java
  jme3-core/src/main/java/com/jme3/light/SpotLight.java
  jme3-core/src/main/java/com/jme3/util/DistanceUtils.java
Labels: duplicate, Group 08, Remove Software Clone

#27 Refactor Matrix3f Serialization to Remove Code Duplication #26
  jme3-core/src/main/java/com/jme3/font/Letters.java
  jme3-core/src/main/java/com/jme3/math/Matrix4f.java
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
  jme3-core/src/main/java/com/jme3/shader/bufferobject/layout/RawLayout.java
  jme3-examples/src/main/java/jme3test/app/TestTempVars.java
  jme3-examples/src/main/java/jme3test/light/TestObbVsBounds.java
Labels: duplicate, Group 08

#28 Mahdieh clone
  jme3-core/src/main/java/com/jme3/math/LineSegment.java
Labels: Group 08, Remove Software Clone
